service: shorturl

provider:
  name: aws
  runtime: nodejs6.10
  stage: v1
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-northeast-1:*:*"

functions:
  short2long:
    handler: handler.short2long
    timeout: 30
    events:
      - http:
          path: /
          method: get
  long2short:
    handler: handler.long2short
    timeout: 30
    events:
      - http:
          path: /url
          method: get
resources:
  Resources:
    shorturl:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: shorturl
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    shorturlSequence:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: shorturl_sequence
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
